name: CD
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  Deploy-AWS:
    env:
      MOLLIE_CONFIG: ${{ secrets.MOLLIE_CONFIG_JSON }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: build
        run: npm run zip-lambda

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: get-mollie-payment-methods-lambda
          environment: MOLLIE_CONFIG=${{ secrets.MOLLIE_CONFIG_JSON }}
          zip_file: extension-module.zip
      # - name: Deploy to GCP
      #   uses: google-github-actions/deploy-cloudrun@main
      #   with:
      #     project_id:
      #     service_account_key:
      #     export_default_credentials: true
      # - name: Deploy to Azure
      #   uses: Azure/functions-action@v1.4.3
      #   with:
      #     app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
      #     package: ${{ secrets.AZURE_FUNCTIONAPP_PACKAGE_PATH }} /* Optional */
      #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} /* Optional */
  # Production ready Docker build & deploy etc
