name: CD
on: [workflow_dispatch]
jobs:
  Deploy-AWS:
    env:
      MOLLIE_CONFIG: ${{ secrets.MOLLIE_CONFIG_JSON }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: build_AWS
        run: npm run zip-lambda

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: get-mollie-payment-methods-lambda
          environment: MOLLIE_CONFIG=${{ secrets.MOLLIE_CONFIG_JSON }}
          zip_file: extension-module.zip

  Deploy-GCP-Function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build_GCP
        run: npm ci && npm run build && cp build/gcpFunctionHandler.js build/index.js && cp -R node_modules build/

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: mollie-commercetools-function
          runtime: nodejs14
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: europe-west1
          source_dir: build
          entry_point: handler
      # - id: test
      #   run: curl "${{ steps.deploy.outputs.url }}"
      # - name: Deploy to Azure
      #   uses: Azure/functions-action@v1.4.3
      #   with:
      #     app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
      #     package: ${{ secrets.AZURE_FUNCTIONAPP_PACKAGE_PATH }} /* Optional */
      #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} /* Optional */
  # Production ready Docker build & deploy etc
