name: CI
on:
  pull_request:
    branches:
      - develop
jobs:
  # AND Sanity check live envs test deployments
  Dev-Build:
    env:
      MOLLIE_CONFIG: ${{ secrets.MOLLIE_CONFIG_JSON }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build
