name: CI
on:
  pull_request:
    branches:
      - develop
jobs:
  # AND Sanity check live envs test deployments
  Dev-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
